options = [
    [
        'الجمهورية الجزائرية الديمقراطية الشعبية',
        'وزارة التعليم العالي والبحث العلمي',
        'جامعة',
        'كلية',
        'قسم',
        'شعبة',
        'الموسم الجامعي',
        'السنة الجامعية',
        'المقياس',
        'من اعداد الطلبة',
        'من اعداد',
        'من اعداد الطالبتين',
        'الطالبين',
        'لطالبة',
        'الطالب',
        'تحت اشراف',
        'تحت اشراف الاستاذ',
        'اشراف الاستاذة',
        'تخصص',
        'مذكرة تخرج ',
        # 'أعضاء اللجنة المناقشة',
        'بعنوان ',
        'الموسومة',
        'لجنة المناقشة',
        'رئيسا',
        'مقررا',
        'مشرفا',
        'ممتحنا',
        # 'أمام لجنة المناقشة ',
        'تقرير تربص ',
        'شهادة ',
        'الليسانس',
        'الماستر',
    ],
    [
        'People’s Democratic Republic of Algeria',
        'Ministry of Higher Education and Scientific research',
        'Djilali Liabes University of Sidi Bel Abbès',
        'Faculty of Letters, Languages and Arts',
        'Department of English',
        'Academic year',
        'College year',
        'Session',
        'Democratic and Popular Republic of Algeria',
        'Ministry of Higher Education and Scientific Research',
        'Ministry',
        'Djilali Liabes University -  Sidi Bel-Abbes',
        'Faculty of Letters and Languages and Arts, April 16th 1940',
        'Faculty',
        'Department of Foreign Languages',
        'Department',


    ],
    [
        'République algérienne démocratique et populaire',
        'Ministère de l\'Enseignement Supérieur et de la Recherche Scientifique',
        'Ministère',
        'REPUBLIQUE ',
        'Université Djilali Liabes de Sidi Bel Abbès',
        'Faculté des sciences de la nature et de la vie',
        'Département d\'anglais',
        'Année Universitaire',
        'Année académique',
        'Session',
        'Promotion',
        'Présenté par',
        'Domaine',
        'Filière',
        'Spécialité',
        'memoire',
        'DÉPARTEMENT',
        'Pour obtenir le diplôme',
        'Thème',
        'Dirigé par',
        'Élaboré par',
        'Encadrant',
        'Mémoire',
        'pour l’obtention du diplôme',
        'Intitulé du thème',
        'Université',
        'Projet de fin d’étude',
        'Option',
        'Devant le jury composé par',
        'Formation Professionnelle',
        'Institut National Spécialisé',
        'Devant le jury',
        'Encadré par :',
        'Direction de la  Formation et de l’enseignement professionnelle',
        'Année professionnelle',
    ]
]
